version: "3"

services: 
    pptp:
        restart: always
        build: 
            context: .
            dockerfile: ./Dockerfile
        network_mode: host
        ports: ["1723:1723"]
        volumes: 
            - ./chap-secrets:/etc/ppp/chap-secrets